


spring:
  application:
    name: springcloud-provider-user
  datasource:
    password: 980917
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.140:3306/zhaopin?serverTimezone=Hongkong
    username: root
  #cloud:
    #config:
      #label: master
      #profile: dev
      #discovery:
        #enabled: true
        #service-id: springcloud-config

  redis:
      host: localhost
      jedis:
        pool:
          max-active: 8
          max-idle: 30
          max-wait: 10000
          min-idle: 10
      port: 6379

mybatis:
     config-locations: classpath:mybatis/confg.xml
     mapper-locations: classpath:mybatis/mapper/*.xml
     type-aliases-package: com.jk.model

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8079
