


spring:
  application:
    name: springcloud-provider-user
  datasource:
    password: 980917
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.112:3306/zhaopin?serverTimezone=Hongkong
    username: root


  redis:
      host: 192.168.1.135
      jedis:
        pool:
          max-active: 8
          max-idle: 30
          max-wait: 10000
          min-idle: 10
      port: 6379

mybatis:
     mapper-locations: classpath:mybatis/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8079
