
spring:
  application:
    name: springcloud-provider-qiye
  datasource:
      password: 980917
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.140:3306/zhaopin?serverTimezone=Hongkong
      username: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8094
mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.jk.model


